apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres
          command: ['sh', '-c', 
          'until pg_isready -h postgres-cluster-ip-service -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
        - name: server
          image: chauyiu1994/multi-server
          ports:
            - containerPort: 5000
          # env var should all be string
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            # get env from secret object
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  # secret object name
                  name: pgpassword
                  # key name in the object
                  key: PGPASSWORD
